services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_WEB3FORMS_KEY=${VITE_WEB3FORMS_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - GMAIL_PASSKEY=${GMAIL_PASSKEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: always
