// Skills images - using public folder paths for Vite
// Place your skill SVGs in public/skills/ folder

const skillsImageMap = {
  'gcp': '/skills/gcp.svg',
  'html': '/skills/html.svg',
  'photoshop': '/skills/photoshop.svg',
  'docker': '/skills/docker.svg',
  'illustrator': '/skills/illustrator.svg',
  'adobe xd': '/skills/adobe-xd.svg',
  'after effects': '/skills/after-effects.svg',
  'css': '/skills/css.svg',
  'angular': '/skills/angular.svg',
  'javascript': '/skills/javascript.svg',
  'next js': '/skills/nextJS.svg',
  'nuxt js': '/skills/nuxtJS.svg',
  'react': '/skills/react.svg',
  'svelte': '/skills/svelte.svg',
  'typescript': '/skills/typescript.svg',
  'vue': '/skills/vue.svg',
  'bootstrap': '/skills/bootstrap.svg',
  'bulma': '/skills/bulma.svg',
  'capacitorjs': '/skills/capacitorjs.svg',
  'coffeescript': '/skills/coffeescript.svg',
  'memsql': '/skills/memsql.svg',
  'mongodb': '/skills/mongoDB.svg',
  'mysql': '/skills/mysql.svg',
  'postgresql': '/skills/postgresql.svg',
  'tailwind': '/skills/tailwind.svg',
  'vitejs': '/skills/vitejs.svg',
  'vuetifyjs': '/skills/vuetifyjs.svg',
  'c': '/skills/c.svg',
  'c++': '/skills/cplusplus.svg',
  'c#': '/skills/csharp.svg',
  'dart': '/skills/dart.svg',
  'go': '/skills/go.svg',
  'java': '/skills/java.svg',
  'kotlin': '/skills/kotlin.svg',
  'julia': '/skills/julia.svg',
  'matlab': '/skills/matlab.svg',
  'php': '/skills/php.svg',
  'python': '/skills/python.svg',
  'ruby': '/skills/ruby.svg',
  'swift': '/skills/swift.svg',
  'canva': '/skills/canva.svg',
  'figma': '/skills/figma.svg',
  'flutter': '/skills/flutter.svg',
  'git': '/skills/git.svg',
  'haxe': '/skills/haxe.svg',
  'ionic': '/skills/ionic.svg',
  'markdown': '/skills/markdown.svg',
  'microsoft office': '/skills/microsoftoffice.svg',
  'picsart': '/skills/picsart.svg',
  'sketch': '/skills/sketch.svg',
  'unity': '/skills/unity.svg',
  'wolframalpha': '/skills/wolframalpha.svg',
  'aws': '/skills/aws.svg',
  'azure': '/skills/azure.svg',
  'blender': '/skills/blender.svg',
  'deno': '/skills/deno.svg',
  'django': '/skills/django.svg',
  'fastify': '/skills/fastify.svg',
  'firebase': '/skills/firebase.svg',
  'gimp': '/skills/gimp.svg',
  'graphql': '/skills/graphql.svg',
  'lightroom': '/skills/lightroom.svg',
  'materialui': '/skills/materialui.svg',
  'nginx': '/skills/nginx.svg',
  'numpy': '/skills/numpy.svg',
  'opencv': '/skills/opencv.svg',
  'premiere pro': '/skills/premierepro.svg',
  'prisma': '/skills/prisma.svg',
  'pytorch': '/skills/pytorch.svg',
  'selenium': '/skills/selenium.svg',
  'strapi': '/skills/strapi.svg',
  'tensorflow': '/skills/tensorflow.svg',
  'webix': '/skills/webix.svg',
  'wordpress': '/skills/wordpress.svg',
  'adobe audition': '/skills/adobeaudition.svg',
  'pandas': '/skills/pandas.svg',
  'scikit-learn': '/skills/scikit-learn.svg',
  '.net': '/skills/dotnet.svg',
  '.net core': '/skills/dotnetcore.svg',
  'kubernetes': '/skills/kubernetes.svg',
  'linux': '/skills/linux.svg',
  'sqlalchemy': '/skills/sqlalchemy.svg',
  'fastapi': '/skills/fastapi.svg',
}

export const skillsImage = (skill) => {
  const skillID = skill.toLowerCase()
  return skillsImageMap[skillID] || '/skills/default.svg'
}
